[32m2024-03-01 17:23:41 -0300[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - b5ea0689-a658-4aee-bbff-5bd3087526a0 - 211816 - LOGS_CAPTURED - Started capturing logs in process (pid: 211816).
[32m2024-03-01 17:23:41 -0300[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - b5ea0689-a658-4aee-bbff-5bd3087526a0 - 211816 - model_data - STEP_START - Started execution of step "model_data".
[32m2024-03-01 17:23:41 -0300[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - b5ea0689-a658-4aee-bbff-5bd3087526a0 - model_data - Loading file from: /home/antonio/Desktop/Recommender_movie_system/movies_dagster/home/storage/keras_dot_product_model using PickledObjectFilesystemIOManager...
2024-03-01 17:23:58.576678: E tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:268] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
[32m2024-03-01 17:23:58 -0300[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - b5ea0689-a658-4aee-bbff-5bd3087526a0 - 211816 - model_data - ASSET_OBSERVATION - ASSET_OBSERVATION for step model_data
[32m2024-03-01 17:23:58 -0300[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - b5ea0689-a658-4aee-bbff-5bd3087526a0 - 211816 - model_data - LOADED_INPUT - Loaded input "keras_dot_product_model" using input manager "io_manager", from output "result" of step "keras_dot_product_model"
[32m2024-03-01 17:23:58 -0300[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - b5ea0689-a658-4aee-bbff-5bd3087526a0 - 211816 - model_data - STEP_INPUT - Got input "keras_dot_product_model" of type "Any". (Type check passed).
2024/03/01 17:23:58 WARNING mlflow.models.signature: Failed to infer the model signature from the input example. Reason: ValueError('in user code:\n\n    File "/home/antonio/anaconda3/envs/dagster-mlops/lib/python3.9/site-packages/keras/src/engine/training.py", line 2416, in predict_function  *\n        return step_function(self, iterator)\n    File "/home/antonio/anaconda3/envs/dagster-mlops/lib/python3.9/site-packages/keras/src/engine/training.py", line 2401, in step_function  **\n        outputs = model.distribute_strategy.run(run_step, args=(data,))\n    File "/home/antonio/anaconda3/envs/dagster-mlops/lib/python3.9/site-packages/keras/src/engine/training.py", line 2389, in run_step  **\n        outputs = model.predict_step(data)\n    File "/home/antonio/anaconda3/envs/dagster-mlops/lib/python3.9/site-packages/keras/src/engine/training.py", line 2357, in predict_step\n        return self(x, training=False)\n    File "/home/antonio/anaconda3/envs/dagster-mlops/lib/python3.9/site-packages/keras/src/utils/traceback_utils.py", line 70, in error_handler\n        raise e.with_traceback(filtered_tb) from None\n    File "/home/antonio/anaconda3/envs/dagster-mlops/lib/python3.9/site-packages/keras/src/engine/input_spec.py", line 219, in assert_input_compatibility\n        raise ValueError(\n\n    ValueError: Layer "model" expects 2 input(s), but it received 1 input tensors. Inputs received: [<tf.Tensor \'IteratorGetNext:0\' shape=(None, 2) dtype=int64>]\n'). To see the full traceback, set the logging level to DEBUG via `logging.getLogger("mlflow").setLevel(logging.DEBUG)`. To disable automatic signature inference, set `signature` to `False` in your `log_model` or `save_model` call.
2024/03/01 17:23:58 WARNING mlflow.tensorflow: You are saving a TensorFlow Core model or Keras model without a signature. Inference with mlflow.pyfunc.spark_udf() will not work unless the model's pyfunc representation accepts pandas DataFrames as inference inputs.
2024/03/01 17:24:19 WARNING mlflow.utils.environment: Encountered an unexpected error while inferring pip requirements (model URI: /tmp/tmpwzcnmha0/model, flavor: tensorflow), fall back to return ['tensorflow==2.14.0']. Set logging level to DEBUG to see the full traceback.
Successfully registered model 'keras_dot_product_model'.
2024/03/01 17:24:19 INFO mlflow.store.model_registry.abstract_store: Waiting up to 300 seconds for model version to finish creation. Model name: keras_dot_product_model, version 1
Created version '1' of model 'keras_dot_product_model'.
[32m2024-03-01 17:24:19 -0300[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - b5ea0689-a658-4aee-bbff-5bd3087526a0 - 211816 - model_data - STEP_OUTPUT - Yielded output "result" of type "Any". (Type check passed).
[32m2024-03-01 17:24:19 -0300[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - b5ea0689-a658-4aee-bbff-5bd3087526a0 - model_data - Writing file at: /home/antonio/Desktop/Recommender_movie_system/movies_dagster/home/storage/model_data using PickledObjectFilesystemIOManager...
[32m2024-03-01 17:24:19 -0300[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - b5ea0689-a658-4aee-bbff-5bd3087526a0 - 211816 - model_data - ASSET_MATERIALIZATION - Materialized value model_data.
[32m2024-03-01 17:24:19 -0300[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - b5ea0689-a658-4aee-bbff-5bd3087526a0 - 211816 - model_data - HANDLED_OUTPUT - Handled output "result" using IO manager "io_manager"
[32m2024-03-01 17:24:19 -0300[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - b5ea0689-a658-4aee-bbff-5bd3087526a0 - 211816 - model_data - STEP_SUCCESS - Finished execution of step "model_data" in 20.86s.
