[0m23:59:44.891873 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fc1edcf05b0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fc1eb9164c0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fc1eb916e20>]}


============================== 23:59:44.895346 | 0b07935c-1ae1-4d7e-9031-0f0409344c62 ==============================
[0m23:59:44.895346 [info ] [MainThread]: Running with dbt=1.7.4
[0m23:59:44.896265 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'version_check': 'True', 'log_path': 'logs', 'debug': 'False', 'profiles_dir': '/home/antonio/.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt debug', 'log_format': 'default', 'introspect': 'True', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m23:59:44.896932 [info ] [MainThread]: dbt version: 1.7.4
[0m23:59:44.897401 [info ] [MainThread]: python version: 3.9.18
[0m23:59:44.897836 [info ] [MainThread]: python path: /home/antonio/anaconda3/envs/mlops-dbt-mrs/bin/python
[0m23:59:44.898259 [info ] [MainThread]: os info: Linux-6.2.0-37-generic-x86_64-with-glibc2.35
[0m23:59:44.990079 [info ] [MainThread]: Using profiles dir at /home/antonio/.dbt
[0m23:59:44.990525 [info ] [MainThread]: Using profiles.yml file at /home/antonio/.dbt/profiles.yml
[0m23:59:44.990952 [info ] [MainThread]: Using dbt_project.yml file at /home/antonio/Desktop/Recommender_movie_system/movies_dagster/dbt_project.yml
[0m23:59:44.991372 [error] [MainThread]: Encountered an error:
Internal Error
  Profile should not be None if loading profile completed
[0m23:59:44.992078 [debug] [MainThread]: Resource report: {"command_name": "debug", "command_wall_clock_time": 0.14104412, "process_user_time": 1.664858, "process_kernel_time": 0.084859, "process_mem_max_rss": "100160", "process_in_blocks": "75672", "process_out_blocks": "8", "command_success": false}
[0m23:59:44.992620 [debug] [MainThread]: Command `dbt debug` failed at 23:59:44.992478 after 0.14 seconds
[0m23:59:44.992994 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fc1edcf05b0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fc1eb939340>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fc1eb5ac550>]}
[0m23:59:44.993383 [debug] [MainThread]: Flushing usage events
